<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class MonthWork extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('month_work', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('staff_id');
            $table->integer('company_id');
            $table->timestamps();
            $table->integer('created_id')->nullable();
            $table->integer('updated_id')->nullable();
            $table->integer('work_month');
            $table->date('start_date');
            $table->date('end_date');
            $table->integer('labor_condition_id');
            $table->integer('employment_type_id')->nullable();
            $table->integer('main_group_id')->nullable();
            $table->integer('pay_type');
            $table->integer('fixed_working_time_month');
            $table->integer('legal_working_time_day')->nullable();
            $table->integer('legal_working_time_week')->nullable();
            $table->integer('legal_working_time_month')->nullable();
            $table->integer('work_time');
            $table->integer('actual_working_time');
            $table->integer('average_work_time');
            $table->integer('fixed_working_time');
            $table->integer('total_overtime');
            $table->integer('rest_time');
            $table->integer('overtime');
            $table->integer('night_time');
            $table->integer('night_overtime');
            $table->integer('holiday_time');
            $table->integer('holiday_overtime');
            $table->integer('holiday_night_time');
            $table->integer('holiday_night_overtime');
            $table->integer('total_night_time');
            $table->integer('prescribed_holiday_work_time');
            $table->integer('prescribed_holiday_overtime');
            $table->integer('prescribed_holiday_night_time');
            $table->integer('prescribed_holiday_night_overtime');
            $table->integer('legal_holiday_work_time');
            $table->integer('legal_holiday_overtime');
            $table->integer('legal_holiday_night_time');
            $table->integer('legal_holiday_night_overtime');
            $table->integer('legal_overtime');
            $table->integer('non_legal_overtime');
            $table->integer('legal_night_overtime');
            $table->integer('non_legal_night_overtime');
            $table->integer('prescribed_legal_overtime');
            $table->integer('prescribed_non_legal_overtime');
            $table->integer('prescribed_legal_night_overtime');
            $table->integer('prescribed_non_legal_night_overtime');
            $table->integer('legal_holiday_legal_overtime');
            $table->integer('legal_holiday_non_legal_overtime');
            $table->integer('legal_holiday_legal_night_overtime');
            $table->integer('legal_holiday_non_legal_night_overtime');
            $table->integer('week_overtime');
            $table->integer('week_night_overtime');
            $table->jsonb('total_time_list')->nullable();
            $table->integer('early_extra_time');
            $table->integer('extra_time');
            $table->integer('late_time');
            $table->integer('early_time');
            $table->integer('as_ot')->nullable();
            $table->integer('annual_paid_time');
            $table->integer('compensatory_day_off_time')->nullable();
            $table->integer('substitution_holiday_time')->nullable();
            $table->integer('absent_hours');
            $table->integer('calendar_days');
            $table->double('working_days_1',20,4);
            $table->double('working_days_2',20,4);
            $table->double('legal_holiday_days',20,4);
            $table->double('prescribed_holiday_days',20,4);
            $table->double('holiday_work_days',20,4);
            $table->double('annual_paid_days',20,4);
            $table->double('absence_days',20,4);
            $table->integer('fixed_working_days');
            $table->double('prescribed_holiday_work_days',20,4);
            $table->double('compensatory_day_off_days',20,4)->nullable();
            $table->double('legal_holiday_work_days',20,4);
            $table->double('substitution_holiday_work_days',20,4)->nullable();
            $table->double('substitution_holiday_days',20,4)->nullable();
            $table->decimal('average_wage',19,4)->nullable();
            $table->decimal('labor_cost',19,4);
            $table->decimal('fixed_working_cost',19,4);
            $table->decimal('total_overtime_cost',19,4);
            $table->decimal('commutation_allowance',19,4);
            $table->decimal('transportation_expenses',19,4);
            $table->integer('commutation_allowance_count');
            $table->integer('transportation_expenses_count');
            $table->integer('transportation_type')->nullable();
            $table->integer('working_count');
            $table->integer('late_count');
            $table->integer('early_count');
            $table->integer('late_early_count');
            $table->integer('personal_approval_count');
            $table->integer('group_approval_count');
            $table->integer('main_group_approval_count');
            $table->integer('company_approval_count');
            $table->jsonb('attendance_type_result')->nullable();
            $table->jsonb('allowances_deductions')->nullable();
            $table->decimal('allowance',19,4);
            $table->decimal('deduction',19,4);
            $table->date('agreement_on_overtime_date')->nullable();
            $table->integer('fixed_working_hours_day')->nullable();
            $table->integer('fixed_working_hours_week')->nullable();
            $table->integer('the_day_paid_count')->nullable();
            $table->integer('paid_count_in_advance')->nullable();
            $table->integer('overtime_count')->nullable();
            $table->integer('night_time_count')->nullable();
            $table->integer('saturday_work_time')->nullable();
            $table->integer('saturday_work_count')->nullable();
            $table->integer('sunday_work_time')->nullable();
            $table->integer('sunday_work_count')->nullable();
            $table->integer('public_holiday_work_time')->nullable();
            $table->integer('public_holiday_work_count')->nullable();
            $table->double('working_days',20,4)->nullable();
            $table->double('paid_leave_used_days',20,4)->nullable();
            $table->integer('paid_leave_used_time')->nullable();
            $table->integer('position_id')->nullable();
            $table->jsonb('annual_leave_pattern')->nullable();
            $table->integer('total_prediction_overtime');
            $table->integer('prediction_work_time')->nullable();
            $table->integer('means_of_transportation')->nullable();
            $table->integer('commuting_distance_car')->nullable();
            $table->integer('overtime_notification_status')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('month_work');
    }
}
